ASFLAGS_ADDITIONAL = --float_support=fpu32
CCSINSTALLDIR = C:/Users/awear/MY_INS~1/TI-CGT~3.LTS
CCSSCRIPTINGDIR = C:/ti/ccs1270/ccs/ccs_base/SCRIPT~1
CONTROLSUITEINSTALLDIR = 
C2000WAREINSTALLDIR = C:/ti/c2000/C2000W~2
CCSARMINSTALLDIR = C:/Users/awear/MY_INS~1/TI-CGT~4.LTS
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~1/MATLAB/R2024b/toolbox/c2b/tic2000
STACK_SIZE = 512
